# Generated by Django 4.1.3 on 2022-11-14 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countrymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='statemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50, null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registaration.countrymodel')),
            ],
        ),
        # migrations.CreateModel(
        #     name ='Employeecrud',
        #     fields =[
        #         ('id',
        #           models.AutoField(
        #           auto_created = True,
        #           primary_key = True,
        #           serialize = False,
        #           verbose_name ='ID'
        #         )),
        #         ('dateofbirth', models.DateField()),
        #     ],
        # ),
    ]
