# Generated by Django 4.1.3 on 2022-11-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registaration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeecrud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=255, null=True)),
                ('Lastname', models.CharField(max_length=255, null=True)),
                ('mobile_no', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('address', models.CharField(max_length=255, null=True, unique=True)),
                ('isactive', models.BooleanField(default=True)),
                ('countryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registaration.countrymodel')),
                ('stateId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registaration.statemodel')),
            ],
        ),
    ]
