# Generated by Django 4.1.3 on 2022-11-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registaration', '0002_employeecrud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecrud',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeecrud',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
