# Generated by Django 4.1.3 on 2022-11-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registaration', '0003_alter_employeecrud_address_alter_employeecrud_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecrud',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50),
        ),
    ]
