# Generated by Django 4.1.3 on 2022-11-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registaration', '0005_alter_employeecrud_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecrud',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='MainTask/static', verbose_name='photo'),
        ),
    ]
