# Generated by Django 4.1.3 on 2022-11-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registaration', '0006_employeecrud_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecrud',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
    ]
