# Generated by Django 4.1.3 on 2022-11-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registaration', '0007_employeecrud_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecrud',
            name='dateofjoining',
            field=models.DateField(null=True),
        ),
    ]
