# Generated by Django 4.0.6 on 2022-11-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registaration', '0009_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecrud',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='MainTask/static/', verbose_name='photo'),
        ),
    ]
