# Generated by Django 4.0.6 on 2022-11-16 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registaration', '0011_checkboxmany'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecrud',
            name='checkbox_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registaration.checkbox'),
        ),
    ]
