# Generated by Django 4.0.6 on 2022-11-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registaration', '0012_employeecrud_checkbox_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecrud',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50),
        ),
    ]
