# Generated by Django 4.0.6 on 2022-11-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registaration', '0013_alter_employeecrud_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecrud',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Registaration/static/', verbose_name='photo'),
        ),
    ]
