# Generated by Django 4.0.6 on 2022-11-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registaration', '0015_alter_employeecrud_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecrud',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50),
        ),
    ]
