# Generated by Django 4.0.6 on 2022-11-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registaration', '0016_alter_employeecrud_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecrud',
            name='checkbox_id',
        ),
    ]
